[cloud_infra_center] Add http proxy support and fix duplicated DNS re…
IBM/z_ansible_collections_samples pull request #129
Opened 2021-11-25 10:30 UTC by shhull

1. Avoid add path: /etc/hostname twice
2. Expose proxy setting in UPI inventory file
3. Add ReadMe for http_proxy setting

2021-11-26 10:11 UTC, bjhuangr requested changes

2021-11-26 10:11 UTC, bjhuangr commented on z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
> +    - If you use your own existing DNS and HAProxy server for the Red Hat OpenShift installation, the bastion server **is not** required.
existing DNS server and load balancer

2021-11-27 09:57 UTC, shhull commented on z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
> +    - If you use your own existing DNS and HAProxy server for the Red Hat OpenShift installation, the bastion server **is not** required.
thx, I've updated it.

2021-11-29 03:38 UTC, bjhuangr approved these changes

2021-11-29 03:38 UTC, merged