volume module sample playbook
IBM/z_ansible_collections_samples pull request #182
Opened 2023-01-24 00:26 UTC by ketankelkar

add volume initialization sample playbook which leverages the zos_ickdsf_init module

Signed-off-by: Ketan Kelkar <ktnklkr@gmail.com>

2023-03-27 20:54 UTC, ketankelkar commented
an idea from a discussion with @dan-jast and myself was to have a scenario available where a volume is initialized and a ZFS mount is set up (leverage zos_mount) -- i see two options, either modify the existing playbook to set up a file system and copy over JCL to a Unix Systems Services file (rather than the current copy to a member) and submit the job from that environment. Alternatively, add a parallel playbook that sets up the volume, the ZFS mount and run JCL there

2023-04-28 23:40 UTC, ddimatos requested changes
2 small comments, otherwise this looks great, thanks @ketankelkar

2023-04-28 23:40 UTC, ddimatos commented on zos_concepts/volume_management/volume_initialization/init_dasd_vol_and_run_sample_jcl/files/HELLO.jcl
> +//* NOTE THAT THE EXCLAMATION POINT IS INVALID EBCDIC FOR JCL
This is an irrelevant old comment probably when doing some negative testing. Probably don't need that. 
//* NOTE THAT THE EXCLAMATION POINT IS INVALID EBCDIC FOR JCL
AND WILL CAUSE A JCL ERROR

2023-04-28 23:40 UTC, ddimatos commented on zos_concepts/volume_management/volume_initialization/init_dasd_vol_and_run_sample_jcl/inventories/group_vars/all.yml
> +  LANG: "C"
We should add the new environment variable here and describe it below.

2023-04-29 04:08 UTC, ddimatos approved these changes
Thanks for the updates, looks good @ketankelkar

2023-04-29 04:08 UTC, merged