add catalog and managed acbs
IBM/z_ansible_collections_samples pull request #220
Opened 2023-06-16 20:18 UTC by steph-lieu

add enablement of catalog and managed acbs playbook

2023-06-30 22:41 UTC, itsBryantP commented
what are the minimum versions for dependencies required for this sample? Those should be documented 
- ansible-core
- IMS collection 
- z/OS Core collection
- ZOAU 
- PYZ

2023-06-30 22:47 UTC, steph-lieu commented
> 

They are added to the roles readme, it needs to be added to the main page? These are what I used when I was working with core 1.4.0 and IMS collection 1.2.0

    ansible-core: 2.11.1
    IMS collection: 1.2.0
    z/OS Core collection: 1.4.0
    ZOAU: 1.1.1
    PYZ: 3.8

2023-06-30 23:05 UTC, itsBryantP commented
> > 
> 
> They are added to the roles readme, it needs to be added to the main page? These are what I used when I was working with core 1.4.0 and IMS collection 1.2.0
> 
> ```
> ansible-core: 2.11.1
> IMS collection: 1.2.0
> z/OS Core collection: 1.4.0
> ZOAU: 1.1.1
> PYZ: 3.8
> ```
Yes can we document this on the top level readme for this sample.
IMS 1.2.0 states support for Python 3.9+ only. Can the required Python version be updated also?

2023-06-30 23:20 UTC, itsBryantP requested changes

2023-06-30 23:20 UTC, itsBryantP commented on zos_subsystems/ims/enable_catalog_macb/successful_macb_example.txt
remove ec hostname in sample output and replace with generic hostname.

2023-06-30 23:28 UTC, itsBryantP commented
Appears that https://github.com/stephanie-lieu is not active. Can we remove that user id from the support sections and only user @steph-lieu

2023-06-30 23:28 UTC, itsBryantP commented
additional updates for review here https://github.com/steph-lieu/z_ansible_collections_samples/pull/1

2023-07-01 00:13 UTC, steph-lieu commented on zos_subsystems/ims/enable_catalog_macb/host_vars/zos_host.yml
> +DFS_DS_VOLUME2: USER01
removed the `DFS_DS_VOLUME2` from the file, `DFS_DS_VOLUME1` is used

2023-07-01 00:22 UTC, steph-lieu commented on zos_subsystems/ims/enable_catalog_macb/successful_macb_example.txt
changed host name & target user & volume

2023-07-06 22:35 UTC, itsBryantP approved these changes

2023-07-07 00:19 UTC, itsBryantP approved these changes

2023-07-07 00:22 UTC, merged