Catalog macb fix
IBM/z_ansible_collections_samples pull request #245
Opened 2024-02-19 19:33 UTC by steph-lieu

2024-02-21 21:05 UTC, jashnani requested changes
Looks good overall. Let's add a brief summary of the testing performed as part of this effort to the PR description for reference. Have a few questions and suggestions below.

2024-02-21 21:37 UTC, steph-lieu commented on zos_subsystems/ims/ims_provisioning/README.md
> +- [**image_copy**](roles/image_copy/README.md) - creates and deletes image copies of IMS catalog
Yes -- I have renamed it to `ims_catalog_image_copy`

2024-02-21 21:38 UTC, steph-lieu commented on zos_subsystems/ims/ims_provisioning/roles/image_copy/README.md
> +[IBM&reg; z/OS&reg; IMS collection 1.3.0-beta.1](https://galaxy.ansible.com/ibm/ibm_zos_ims)
Changed -- also changed the core collection to 1.5.0 or later

2024-02-22 21:00 UTC, steph-lieu commented on zos_subsystems/ims/ims_provisioning/ansible.cfg
> +#ssh_args = -C -o ControlMaster=auto -o ControlPersist=1200s -o PreferredAuthentications=publickey -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
Tested with it uncommented and it still works. Originally uncommented to try a workaround for core 1.5.0, that didn't end up working out.

2024-02-22 22:03 UTC, steph-lieu commented on zos_subsystems/ims/ims_provisioning/roles/ims_common/tasks/main.yml
> +      ignore_errors: true
Changed to back to 30 seconds and added comments to explain why we are ignoring errors.
Was originally 60 to experiment and test changes for the error related to the IMS Connect.

2024-02-22 23:34 UTC, jashnani approved these changes
Thanks for addressing the feedback. Looks good!

2024-02-22 23:38 UTC, merged