[Module][Playbook][1720]Playbook_zfs_resize
IBM/z_ansible_collections_samples pull request #295
Opened 2024-12-26 16:53 UTC by AndreMarcel99

##### SUMMARY

Add playbooks about cases to works with gds.

##### ISSUE TYPE

- Enabler Pull Request

2025-02-25 20:40 UTC, fernandofloresg requested changes

2025-02-25 20:40 UTC, fernandofloresg commented on zos_concepts/zfsadm/grow_zfs_fetch_full_trace_back/site.yml
> +# Upon successful dependency analyais, the z/OS playbook will be executed.
```suggestion
# Upon successful dependency analysis, the z/OS playbook will be executed.
```

2025-02-25 20:40 UTC, fernandofloresg commented on zos_concepts/zfsadm/shrink_zfs_different_size_and_verbose/shrink_zfs_different_size_and_verbose.yml
> +# This sample playbook demonstrates how to create a new Generation Data Group(GDG),
This description also looks like is from GDG.

2025-02-25 20:40 UTC, fernandofloresg commented on README.md
> +  - [Shrink on different size and see full verbose](zos_concepts/zfsadm/shrink_zfs_different_size_and_verbose)
```suggestion
  - [Shrink ZFS and see full verbose](zos_concepts/zfsadm/shrink_zfs_different_size_and_verbose)
```

2025-03-16 02:05 UTC, fernandofloresg approved these changes
Leaving a possible grammar improvement

2025-03-16 02:05 UTC, fernandofloresg commented on README.md
> +  - [Grow ZFS fetch and full trace back](zos_concepts/zfsadm/grow_zfs_fetch_full_trace_back)
```suggestion
  - [Grow ZFS and fetch full trace back](zos_concepts/zfsadm/grow_zfs_fetch_full_trace_back)
```

2025-03-19 17:17 UTC, rexemin requested changes
Looks really good, I just left a bunch of suggestions regarding the comments and task names in the playbooks.

2025-03-19 19:54 UTC, rexemin approved these changes

2025-04-02 18:39 UTC, merged